### ISSUE TITLE
Full farmer doesn't delete expired shards

### ISSUE THREAD

**Issue by littleskunk** [Storj/core#636]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
daemon: 2.1.2, core: 6.0.15, protocol: 1.1.0
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

I have written a simple script to print out the farmer contracts. Rocket chat user yury executed it a few days ago. His farmer was full (101%) and the cleanup job was not working correct.
```
{
"CurrentTime": 1484941844117,
"CurrentDate": "2017-01-20T19:50:44.117Z",
"501dc5630c84b53cbe37c13f4a6d701f9c297960": {
"xpub6BKMrtzRrthaCvD4yKg2NMre3sr2sqAf7JtYPfQ9rxzxLwugGZ71qvWJnJtzzfrXmG2rmhEdKXdYbXwdJE6jSmXDwfC53QDpVDt1LKUfnMC": {
"MinBegin": 1478844260358,
"MaxBegin": 1481165898267,
"MinEnd": 1486620260358,
"MaxEnd": 1488941898267,
"Contracts": 263649,
"TotalSize": 3692877935744,
"MinEndDate": "2017-02-09T06:04:20.358Z",
"MaxEndDate": "2017-03-08T02:58:18.267Z",
"MinBeginDate": "2016-11-11T06:04:20.358Z",
"MaxBeginDate": "2016-12-08T02:58:18.267Z"
},
"a69d4f2e3e97e4f26ece3d437b2825c5d7fed9e6": {
"MinBegin": 1476565766152,
"MaxBegin": 1478328396966,
"MinEnd": 1484341766152,
"MaxEnd": 1486104396966,
"Contracts": 9157,
"TotalSize": 126445441591,
"MinEndDate": "2017-01-13T21:09:26.152Z",
"MaxEndDate": "2017-02-03T06:46:36.966Z",
"MinBeginDate": "2016-10-15T21:09:26.152Z",
"MaxBeginDate": "2016-11-05T06:46:36.966Z"
},
"593844dc7f0076a1aeda9a6b9788af17e67c1052": {
"MinBegin": 1476563064211,
"MaxBegin": 1478346727688,
"MinEnd": 1484339064211,
"MaxEnd": 1486122727688,
"Contracts": 6568,
"TotalSize": 82496789709,
"MinEndDate": "2017-01-13T20:24:24.211Z",
"MaxEndDate": "2017-02-03T11:52:07.688Z",
"MinBeginDate": "2016-10-15T20:24:24.211Z",
"MaxBeginDate": "2016-11-05T11:52:07.688Z"
},
"xpub6AHweYHAxk1EhJSBctQD1nLWPog6Sy2eTpKQLExR1hfzTyyZQWvU4EYNXv1NJN7GpLYXnDLt4PzN874g6zSjAQdFCHZN7U7nbYKYVDUzD42": {
"MinBegin": 1476845670189,
"MaxBegin": 1481165715030,
"MinEnd": 1484621670189,
"MaxEnd": 1488941715030,
"Contracts": 21022,
"TotalSize": 8081856905896,
"MinEndDate": "2017-01-17T02:54:30.189Z",
"MaxEndDate": "2017-03-08T02:55:15.030Z",
"MinBeginDate": "2016-10-19T02:54:30.189Z",
"MaxBeginDate": "2016-12-08T02:55:15.030Z"
},
"xpub6BFGC5yAc1uwJVmDwVyx15FYQYKBRp18DVLyKfbtHds6jqo8oggZLJmz5yDg5fbT1bH3XEnPxrVmy5W6ER541zdMDCbAeGtkm3zNz6NxPhM": {
"MinBegin": 1478758892843,
"MaxBegin": 1478844053410,
"MinEnd": 1486534892843,
"MaxEnd": 1486620053410,
"Contracts": 186,
"TotalSize": 3100468480,
"MinEndDate": "2017-02-08T06:21:32.843Z",
"MaxEndDate": "2017-02-09T06:00:53.410Z",
"MinBeginDate": "2016-11-10T06:21:32.843Z",
"MaxBeginDate": "2016-11-11T06:00:53.410Z"
}
}
}
```
The totalsize is not correct. That is a problem with my script.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Today he executed the script again. He is running the new core release and the cleanup job worked correct. You can see that the old shards are removed now. I would expect new shards but his farmer is still at 101% and not sending any OFFER.
```
{
"CurrentTime": 1485550576079,
"CurrentDate": "2017-01-27T20:56:16.079Z",
"501dc5630c84b53cbe37c13f4a6d701f9c297960": {
"xpub6BKMrtzRrthaCvD4yKg2NMre3sr2sqAf7JtYPfQ9rxzxLwugGZ71qvWJnJtzzfrXmG2rmhEdKXdYbXwdJE6jSmXDwfC53QDpVDt1LKUfnMC": {
"MinBegin": 1478844260358,
"MaxBegin": 1481165898267,
"MinEnd": 1486620260358,
"MaxEnd": 1488941898267,
"Contracts": 263649,
"TotalSize": 3692877935744,
"MinEndDate": "2017-02-09T06:04:20.358Z",
"MaxEndDate": "2017-03-08T02:58:18.267Z",
"MinBeginDate": "2016-11-11T06:04:20.358Z",
"MaxBeginDate": "2016-12-08T02:58:18.267Z"
},
"a69d4f2e3e97e4f26ece3d437b2825c5d7fed9e6": {
"MinBegin": 1477801093514,
"MaxBegin": 1478328396966,
"MinEnd": 1485577093514,
"MaxEnd": 1486104396966,
"Contracts": 4733,
"TotalSize": 53078726912,
"MinEndDate": "2017-01-28T04:18:13.514Z",
"MaxEndDate": "2017-02-03T06:46:36.966Z",
"MinBeginDate": "2016-10-30T04:18:13.514Z",
"MaxBeginDate": "2016-11-05T06:46:36.966Z"
},
"xpub6AHweYHAxk1EhJSBctQD1nLWPog6Sy2eTpKQLExR1hfzTyyZQWvU4EYNXv1NJN7GpLYXnDLt4PzN874g6zSjAQdFCHZN7U7nbYKYVDUzD42": {
"MinBegin": 1477874797566,
"MaxBegin": 1481165715030,
"MinEnd": 1485650797566,
"MaxEnd": 1488941715030,
"Contracts": 21022,
"TotalSize": 8081856905896,
"MinEndDate": "2017-01-29T00:46:37.566Z",
"MaxEndDate": "2017-03-08T02:55:15.030Z",
"MinBeginDate": "2016-10-31T00:46:37.566Z",
"MaxBeginDate": "2016-12-08T02:55:15.030Z"
},
"593844dc7f0076a1aeda9a6b9788af17e67c1052": {
"MinBegin": 1477715034021,
"MaxBegin": 1478346727688,
"MinEnd": 1485491034021,
"MaxEnd": 1486122727688,
"Contracts": 5528,
"TotalSize": 60341345800,
"MinEndDate": "2017-01-27T04:23:54.021Z",
"MaxEndDate": "2017-02-03T11:52:07.688Z",
"MinBeginDate": "2016-10-29T04:23:54.021Z",
"MaxBeginDate": "2016-11-05T11:52:07.688Z"
},
"xpub6BFGC5yAc1uwJVmDwVyx15FYQYKBRp18DVLyKfbtHds6jqo8oggZLJmz5yDg5fbT1bH3XEnPxrVmy5W6ER541zdMDCbAeGtkm3zNz6NxPhM": {
"MinBegin": 1478758892843,
"MaxBegin": 1478844053410,
"MinEnd": 1486534892843,
"MaxEnd": 1486620053410,
"Contracts": 186,
"TotalSize": 3100468480,
"MinEndDate": "2017-02-08T06:21:32.843Z",
"MaxEndDate": "2017-02-09T06:00:53.410Z",
"MinBeginDate": "2016-11-10T06:21:32.843Z",
"MaxBeginDate": "2016-11-11T06:00:53.410Z"
}
}
}
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Farm a few GB.
2. Reduce allocated space to stop sending OFFER.
3. Run cleanup job to delete some shards.

**Comment by littleskunk** [comment]
Workaround: Increase allocated size a littlebit. The farmer will start sending OFFER and new shards will replace the expired shards. The used space should go down slowly. After some time you can set the old allocated size and the farmer should still send OFFER.

**Comment by bookchin** [comment]
Ah, this must be due to the logic for OFFER sending using physical space used and not accounting for the tombstones shards.

**Comment by bookchin** [comment]
This one is tough. Since deletes in KFS (LevelDB) do not actually remove the data from disk, but rather tombstone entries for deletion or overwriting later during compaction, relying solely on the reported disk space is not sufficient to determine if there is remaining room to store further shards.

There's two approaches to fix this I can think of right now:

1. Do not rely on `leveldb#approximateSize` and instead, count the number of keys in each KFS bucket and multiply them by the `C` value to get an accurate size of the shard database.
2. Insert a threshold into the offer logic for determining size that exceeds the allocated space by some reasonable amount to allow new data coming in to overwrite tombstoned data.

Option 1 will very likely impact performance (I will run some benchmarks) negatively and option 2 will very likely lead to issues with committing more space than assigned (or available on disk).

I will experiment with both.

**Comment by bookchin** [comment]
After talking with @braydonf - perhaps the *real* solution here is to submit a PR to [leveldown](https://github.com/Level/leveldown) to expose bindings to [LevelDB's `DBImpl#compactRange` method](https://github.com/google/leveldb/blob/master/db/db_impl.cc#L567) and use that in KFS [when unlinking entries](https://github.com/Storj/kfs/blob/master/lib/s-bucket.js#L221-L245).

**Comment by bookchin** [comment]
Another option is to extend KFS `Sbucket#unlink` to optionally close the DB after unlink is complete, run a `leveldown#repair` to trigger compaction, then write (or possibly read) an special small key to flush the changes.

**Comment by bookchin** [comment]
Tracking at https://github.com/Storj/kfs/pull/42

**Comment by bookchin** [comment]
Related https://github.com/Level/leveldown/pull/340

**Comment by littleskunk** [comment]
```
root@storj:~# npm list kfs
/root
└─┬ storj-lib@6.1.0
  └── kfs@3.1.0
```

```
root@storj:~# node cleanup.js
flushing shards, some buckets will be inaccessbile
Delete shard ff99ca66ac71737af888cfc4279b0a2b5d0cd40b
/root/node_modules/kfs/node_modules/leveldown/leveldown.js:62
  this.binding.compactRange(start, end, callback)
               ^

TypeError: this.binding.compactRange is not a function
    at LevelDOWN.compactRange (/root/node_modules/kfs/node_modules/leveldown/leveldown.js:62:16)
    at Sbucket.flush (/root/node_modules/kfs/lib/s-bucket.js:478:14)
    at _getSbucketForKey (/root/node_modules/kfs/lib/b-table.js:288:17)
    at sBucket.open (/root/node_modules/kfs/lib/b-table.js:162:9)
    at Sbucket._onOpen (/root/node_modules/kfs/lib/s-bucket.js:133:7)
    at Sbucket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Sbucket.emit (events.js:185:7)
    at /root/node_modules/kfs/lib/s-bucket.js:122:14
    at /root/node_modules/abstract-leveldown/abstract-leveldown.js:42:7
```

I would expect to see this error message on storjshare-daemon every 24 hours. I will repeat that test later with your open leveldown pull request.

**Comment by bookchin** [comment]
The latest kfs is pointed at my leveldown fork so reinstalling the dependencies should pull it in and this will not happen.

**Comment by littleskunk** [comment]
I am sorry but you missed one leveldown dependency: https://github.com/Storj/core/blob/master/package.json#L83

```
root@storj:~# npm list leveldown
/root
└─┬ storj-lib@6.1.0
  ├─┬ kfs@3.1.0
  │ └── leveldown@1.5.3  (git://github.com/bookchin/leveldown.git#460cea7136e238121db8b6b218c464dcd0e37090)
  └── leveldown@1.5.3
```

**Comment by bookchin** [comment]
fixed in https://github.com/Storj/core/releases/tag/v6.1.1

**Comment by littleskunk** [comment]
Now we can be sure the pull request is installed and executed but still the same error.
```
flushing shards, some buckets will be inaccessbile                                                                                                                                                                                                               
/root/node_modules/leveldown/leveldown.js:62                                                                                                                                                                                                                     
  this.binding.compactRange(start, end, callback)                                                                                                                                                                                                                
               ^                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                 
TypeError: this.binding.compactRange is not a function                                                                                                                                                                                                           
    at LevelDOWN.compactRange (/root/node_modules/leveldown/leveldown.js:62:16)                                                                                                                                                                                  
    at Sbucket.flush (/root/node_modules/kfs/lib/s-bucket.js:478:14)                                                                                                                                                                                             
    at _getSbucketForKey (/root/node_modules/kfs/lib/b-table.js:288:17)                                                                                                                                                                                          
    at Btable._getSbucketForKey (/root/node_modules/kfs/lib/b-table.js:166:5)                                                                                                                                                                                    
    at async.eachSeries (/root/node_modules/kfs/lib/b-table.js:287:12)                                                                                                                                                                                           
    at /root/node_modules/async/dist/async.js:3025:16                                                                                                                                                                                                            
    at replenish (/root/node_modules/async/dist/async.js:882:17)                                                                                                                                                                                                 
    at /root/node_modules/async/dist/async.js:886:9                                                                                                                                                                                                              
    at eachLimit$1 (/root/node_modules/async/dist/async.js:3114:22)                                                                                                                                                                                              
    at Object.<anonymous> (/root/node_modules/async/dist/async.js:918:16)                                                                                                                                                                                        
    at Btable.flush (/root/node_modules/kfs/lib/b-table.js:286:11)                                                                                                                                                                                               
    at EmbeddedStorageAdapter._flush (/root/node_modules/storj-lib/lib/storage/adapters/embedded.js:163:12)                                                                                                                                                      
    at EmbeddedStorageAdapter.StorageAdapter.flush (/root/node_modules/storj-lib/lib/storage/adapter.js:162:15)                                                                                                                                                  
    at Readable.<anonymous> (/root/cleanup.js:37:20)                                                                                                                                                                                                             
    at emitNone (events.js:86:13)                                                                                                                                                                                                                                
    at Readable.emit (events.js:185:7)                                                                                                                                                                                                                           
root@storj:~# npm list leveldown                                                                                                                                                                                                                                 
/root
└─┬ storj-lib@6.1.1                                                                                                                                                                                                                                              
  └── leveldown@1.5.3  (git://github.com/bookchin/leveldown.git#460cea7136e238121db8b6b218c464dcd0e37090)
```

rocket chat user kadder is getting the same error. He is not using my delete script. He installed the latest storj-libv6.1.1 and reduced the cleanup timer to 15 minutes. He gets the same problem.

**Comment by bookchin** [comment]
Try uninstalling and reinstalling. You have to make sure that the bindings get recompiled.

**Comment by Kadder86** [comment]
I have uninstalled and reinstalled it two times and have the same Issuse

**Comment by bookchin** [comment]
Ah, okay, the problem is that LevelDOWN uses `prebuild` package to avoid having to compile from source, so when installing normally, you get a prebuilt binary (which doesn't include the changes we made to LevelDOWN).

If the open PR to LevelDOWN gets merged, this will no longer be an issue. Until then, use

```
npm install --global --build-from-source storjshare-daemon
```

I will add this to the README - just tested and confirmed.

**Comment by littleskunk** [comment]
Yea its working. Shards are deleted and the space is getting free.
